<?php
namespace exface\Core\CommonLogic\Tasks;

use exface\Core\DataTypes\StringDataType;
use exface\Core\Interfaces\Tasks\ResultDataInterface;
use exface\Core\Interfaces\DataSheets\DataSheetInterface;


/**
 * Generic data result implementation - typical for actions like the core's ReadData, SaveData, etc.
 * 
 * @author Andrej Kabachnik
 *
 */
class ResultData extends ResultMessage implements ResultDataInterface
{
    private $dataSheet = null;
        
    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\ResultInterface::getData()
     */
    public function getData(): DataSheetInterface
    {
        if (is_null($this->dataSheet)) {
            $this->dataSheet = $this->getTask()->getInputData();
        }
        return $this->dataSheet;
    }
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\ResultDataInterface::setData()
     */
    public function setData(DataSheetInterface $dataSheet): ResultDataInterface
    {
        $this->dataSheet = $dataSheet;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\ResultDataInterface::hasData()
     */
    public function hasData(): bool
    {
        return is_null($this->dataSheet) ? false : true;
    }
    
    public function isEmpty() : bool
    {
        return parent::isEmpty() && ! $this->hasData();
    }

    /**
     *  
     * @return string
     */
    public function getMessage(): string
    {
        // If there is a custom result message text defined, use it instead of the autogenerated message
        $message = parent::getMessage();        
        $placeholders = StringDataType::findPlaceholders($message);
        if (! empty($placeholders)) {
            $messageLineWithPlaceholders = $message;
            $message = '';
            foreach ($this->getData()->getRows() as $row) {
                foreach ($placeholders as $ph) {
                    $message_line = str_replace('[#' . $ph . '#]', $row[$ph], $messageLineWithPlaceholders);
                }
                $message .= ($message ? "\n" : '') . $message_line;
            }
        }

        return $message;
    }
}