<?php
namespace exface\Core\CommonLogic\Tasks;

use exface\Core\Interfaces\DataSheets\DataSheetInterface;
use exface\Core\Interfaces\Tasks\TaskInterface;
use exface\Core\Interfaces\Tasks\TaskResultInterface;

/**
 * Generic task result implementation.
 * 
 * @author Andrej Kabachnik
 *
 */
class TaskResultMessage implements TaskResultInterface
{
    private $task = null;
    
    private $isDataModified = false;
    
    private $message = null;
    
    private $isUndoable = false;
    
    private $workbench = null;
    
    /**
     * 
     * @param TaskInterface $task
     */
    public function __construct(TaskInterface $task)
    {
        $this->task = $task;
        $this->workbench = $task->getWorkbench();
    }
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\TaskResultInterface::setDataModified()
     */
    public function setDataModified(bool $value): TaskResultInterface
    {
        $this->isDataModified = $value;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\TaskResultInterface::isUndoable()
     */
    public function isUndoable(): bool
    {
        return $this->isUndoable;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\TaskResultInterface::setUndoable()
     */
    public function setUndoable(bool $trueOrFalse): TaskResultInterface
    {
        $this->isUndoable = $trueOrFalse;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\TaskResultInterface::isDataModified()
     */
    public function isDataModified(): bool
    {
        return $this->isDataModified;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\TaskResultInterface::getMessage()
     */
    public function getMessage(): string
    {
        // If there is a custom result message text defined, use it instead of the autogenerated message
        if (is_null($this->message)) {
            $message = '';
        } else {
            $message = $this->message;
            $placeholders = $this->getWorkbench()->utils()->findPlaceholdersInString($message);
            if ($placeholders) {
                $message = '';
                foreach ($this->getResultDataSheet()->getRows() as $row) {
                    $message_line = $this->getResultMessageText();
                    foreach ($placeholders as $ph) {
                        $message_line = str_replace('[#' . $ph . '#]', $row[$ph], $message_line);
                    }
                    $message .= ($message ? "\n" : '') . $message_line;
                }
            }
        }
        
        return $message;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\ExfaceClassInterface::getWorkbench()
     */
    public function getWorkbench()
    {
        return $this->workbench;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\TaskResultInterface::getTask()
     */
    public function getTask(): TaskInterface
    {
        return $this->task;
    }
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Tasks\TaskResultInterface::setMessage()
     */
    public function setMessage(string $string): TaskResultInterface
    {
        $this->message = $string;
        return $this;
    }
}