<?php
namespace exface\Core\CommonLogic\Model;

use exface\Core\Interfaces\Model\UiPageInterface;
use exface\Core\Interfaces\WidgetInterface;
use exface\Core\Interfaces\TemplateInterface;
use exface\Core\Factories\WidgetFactory;
use exface\Core\Interfaces\UiManagerInterface;
use exface\Core\Exceptions\Widgets\WidgetIdConflictError;
use exface\Core\Interfaces\Widgets\iHaveChildren;
use exface\Core\DataTypes\StringDataType;
use exface\Core\Factories\EventFactory;
use exface\Core\Exceptions\Widgets\WidgetNotFoundError;
use exface\Core\CommonLogic\UxonObject;
use exface\Core\Exceptions\RuntimeException;
use exface\Core\CommonLogic\NameResolver;

/**
 * This is the default implementation of the UiPageInterface.
 * 
 * The first widget without a parent added to the page is concidered to be the
 * main root widget.
 * 
 * Widgets get cached in an internal array.
 * 
 * @see UiPageInterface
 * 
 * @author Andrej Kabachnik
 *
 */
class UiPage implements UiPageInterface
{

    private $widgets = array();

    private $template = null;

    private $ui = null;

    private $widget_root = null;

    private $context_bar = null;

    const WIDGET_ID_SEPARATOR = '_';

    const WIDGET_ID_SPACE_SEPARATOR = '.';

    private $appAlias = null;

    private $updateable = true;

    private $menuParentId = null;

    private $menuParentIdCms = null;

    private $menuParentAlias = null;

    private $menuParentPage = null;

    private $menuIndex = 0;

    private $id = null;

    private $idCms = null;

    private $name = null;

    private $shortDescription = null;

    private $replacesPageAlias = null;

    private $contents = null;

    private $aliasWithNamespace = null;
    
    private $alias = null;
    
    private $namespace = null;

    /**
     *
     * @deprecated use UiPageFactory::create() instead!
     * @param TemplateInterface $template            
     */
    public function __construct(UiManagerInterface $ui)
    {
        $this->ui = $ui;
    }

    /**
     *
     * @param WidgetInterface $widget            
     * @throws WidgetIdConflictError
     * @return \exface\Core\CommonLogic\Model\UiPage
     */
    public function addWidget(WidgetInterface $widget)
    {
        $widget->setIdAutogenerated($this->generateId($widget));
        if ($widget->getIdSpecified() && $widget->getIdSpecified() != $this->sanitizeId($widget->getIdSpecified())) {
            throw new WidgetIdConflictError($widget, 'Explicitly specified id "' . $widget->getIdSpecified() . '" for widget "' . $widget->getWidgetType() . '" not unique on page "' . $this->getId() . '": please specify a unique id for the widget in the UXON description of the page!');
            return $this;
        }
        
        // Remember the first widget added automatically as the root widget of the page
        if (count($this->widgets) === 0 && ! $widget->is('ContextBar')) {
            $this->widget_root = $widget;
        }
        
        $this->widgets[$widget->getId()] = $widget;
        return $this;
    }

    /**
     *
     * @return \exface\Core\Interfaces\WidgetInterface
     */
    public function getWidgetRoot()
    {
        return $this->widget_root;
    }

    /**
     *
     * {@inheritdoc}
     *
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getWidget()
     */
    public function getWidget($id, WidgetInterface $parent = null)
    {
        // First check to see, if the widget id is already in the widget list. If so, return the corresponding widget.
        // Otherwise look throgh the entire tree to make sure, even subwidgets with late binding can be found (= that is
        // those, that are created if a certain property of another widget is accessed.
        if ($widget = $this->widgets[$id]) {
            // FIXME Check if one of the ancestors of the widget really is the given parent. Although this should always
            // be the case, but better doublecheck ist.
            return $widget;
        }
        
        // If the parent is null, look under the root widget
        // FIXME this makes a non-parent lookup in pages with multiple roots impossible.
        if (is_null($parent)) {
            if (StringDataType::startsWith($id . static::WIDGET_ID_SEPARATOR, $this->getContextBar()->getId()) || StringDataType::startsWith($id . static::WIDGET_ID_SPACE_SEPARATOR, $this->getContextBar()->getId())) {
                $parent = $this->getContextBar();
            } else {
                // If the page is empty, no widget can be found ;) ...except the widget, that are always there
                if ($this->isEmpty()) {
                    throw new WidgetNotFoundError('Widget "' . $id . '" not found in page "' . $this->getId() . '": page empty!');
                }
                $parent = $this->getWidgetRoot();
            }
        }
        
        if ($id_space_length = strpos($id, static::WIDGET_ID_SPACE_SEPARATOR)) {
            $id_space = substr($id, 0, $id_space_length);
            $id = substr($id, $id_space_length + 1);
            return $this->getWidgetFromIdSpace($id, $id_space, $parent);
        } else {
            return $this->getWidgetFromIdSpace($id, '', $parent);
        }
    }

    /**
     * 
     * @param string $id
     * @param string $id_space
     * @param WidgetInterface $parent
     * 
     * @throws WidgetNotFoundError if no matching widget was found
     * 
     * @return WidgetInterface
     */
    private function getWidgetFromIdSpace($id, $id_space, WidgetInterface $parent)
    {
        $id_with_namespace = static::addIdSpace($id_space, $id);
        if ($widget = $this->widgets[$id_with_namespace]) {
            // FIXME Check if one of the ancestors of the widget really is the given parent. Although this should always
            // be the case, but better doublecheck ist.
            return $widget;
        }
        
        if ($parent->getId() === $id) {
            return $parent;
        }
        
        if (StringDataType::startsWith($id_space, $parent->getId() . self::WIDGET_ID_SEPARATOR)) {
            $id_space_root = $this->getWidget($id_space, $parent);
            return $this->getWidgetFromIdSpace($id, $id_space, $id_space_root);
        }
        
        $id_is_path = false;
        if (StringDataType::startsWith($id_with_namespace, $parent->getId() . self::WIDGET_ID_SEPARATOR)) {
            $id_is_path = true;
        }
        
        if ($parent instanceof iHaveChildren) {
            foreach ($parent->getChildren() as $child) {
                $child_id = $child->getId();
                if ($child_id == $id_with_namespace) {
                    return $child;
                } else {
                    if (! $id_is_path || StringDataType::startsWith($id_with_namespace, $child_id . self::WIDGET_ID_SEPARATOR)) {
                        // If we are looking for a non-path id or the path includes the id of the child, look within the child
                        try {
                            return $this->getWidgetFromIdSpace($id, $id_space, $child);
                        } catch (WidgetNotFoundError $e) {
                            continue;
                        }
                    } elseif ($id_is_path) {
                        // If the id is a path, but did not include the child id, continie with the next child
                        continue;
                    }
                }
            }
        }
        
        throw new WidgetNotFoundError('Widget "' . $id . '" not found in id space "' . $id_space . '" within parent "' . $parent->getId() . '" on page "' . $this->getId() . '"!');
        
        return;
    }

    private static function addIdSpace($id_space, $id)
    {
        return (is_null($id_space) || $id_space === '' ? '' : $id_space . static::WIDGET_ID_SPACE_SEPARATOR) . $id;
    }

    /**
     * Generates an unique id for the given widget.
     * If the widget has an id already, this is merely sanitized.
     *
     * @param WidgetInterface $widget            
     * @return string
     */
    protected function generateId(WidgetInterface $widget)
    {
        if (! $id = $widget->getId()) {
            if ($widget->getParent()) {
                $id = $widget->getParent()->getId() . self::WIDGET_ID_SEPARATOR;
            }
            $id .= $widget->getWidgetType();
        }
        return $this->sanitizeId($id);
    }

    /**
     * Makes sure, the given widget id is unique in this page.
     * If not, the id gets a numeric index, which makes it unique.
     * Thus, the returned value is guaranteed to be unique!
     *
     * @param string $string            
     * @return string
     */
    protected function sanitizeId($string)
    {
        if ($this->widgets[$string]) {
            $index = substr($string, - 2);
            if (is_numeric($index)) {
                $index_new = str_pad(intval($index + 1), 2, 0, STR_PAD_LEFT);
                $string = substr($string, 0, - 2) . $index_new;
            } else {
                $string .= '02';
            }
            
            return $this->sanitizeId($string);
        }
        return $string;
    }

    /**
     *
     * @return \exface\Core\Interfaces\TemplateInterface
     */
    public function getTemplate()
    {
        if (is_null($this->template)) {
            // FIXME need a method to get the template from the CMS page here somehow. It should probably become a method of the CMS-connector
            // The mapping between CMS-templates and ExFace-templates needs to move to a config variable of the CMS-connector app!
        }
        return $this->template;
    }

    /**
     *
     * @param TemplateInterface $template            
     * @return \exface\Core\CommonLogic\Model\UiPage
     */
    protected function setTemplate(TemplateInterface $template)
    {
        $this->template = $template;
        return $this;
    }

    /**
     *
     * @param string $widget_type            
     * @param WidgetInterface $parent_widget            
     * @param string $widget_id            
     * @return WidgetInterface
     */
    public function createWidget($widget_type, WidgetInterface $parent_widget = null, UxonObject $uxon = null)
    {
        if ($uxon) {
            $uxon->setProperty('widget_type', $widget_type);
            $widget = WidgetFactory::createFromUxon($this, $uxon, $parent_widget);
        } else {
            $widget = WidgetFactory::create($this, $widget_type, $parent_widget);
        }
        return $widget;
    }

    /**
     *
     * @param string $widget_id            
     * @return \exface\Core\CommonLogic\Model\UiPage
     */
    public function removeWidgetById($widget_id)
    {
        unset($this->widgets[$widget_id]);
        return $this;
    }

    /**
     *
     * {@inheritdoc}
     *
     * @see \exface\Core\Interfaces\Model\UiPageInterface::removeWidget()
     */
    public function removeWidget(WidgetInterface $widget, $remove_children_too = true)
    {
        if ($remove_children_too) {
            foreach ($this->widgets as $cached_widget) {
                if ($cached_widget->getParent() === $widget) {
                    $this->removeWidget($cached_widget, true);
                }
            }
        }
        $result = $this->removeWidgetById($widget->getId());
        
        $this->getWorkbench()->eventManager()->dispatch(EventFactory::createWidgetEvent($widget, 'Remove.After'));
        
        return $result;
    }
    
    /**
     * 
     * @return \exface\Core\CommonLogic\Model\UiPage
     */
    public function removeAllWidgets()
    {
        foreach ($this->widgets as $cached_widget) {
            $this->removeWidgetById($cached_widget->getId());
            $this->getWorkbench()->eventManager()->dispatch(EventFactory::createWidgetEvent($cached_widget, 'Remove.After'));
        }
        $this->widgets = [];
        $this->widget_root = null;
        
        return $this;
    }

    /**
     *
     * @return UiManagerInterface
     */
    public function getUi()
    {
        return $this->ui;
    }

    /**
     *
     * {@inheritdoc}
     *
     * @see \exface\Core\Interfaces\ExfaceClassInterface::getWorkbench()
     */
    public function getWorkbench()
    {
        return $this->getUi()->getWorkbench();
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getWidgetIdSeparator()
     */
    public function getWidgetIdSeparator()
    {
        return self::WIDGET_ID_SEPARATOR;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getWidgetIdSpaceSeparator()
     */
    public function getWidgetIdSpaceSeparator()
    {
        return self::WIDGET_ID_SPACE_SEPARATOR;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::isEmpty()
     */
    public function isEmpty()
    {
        return $this->getWidgetRoot() ? false : true;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getContextBar()
     */
    public function getContextBar()
    {
        if (is_null($this->context_bar)) {
            $this->context_bar = WidgetFactory::create($this, 'ContextBar');
        }
        return $this->context_bar;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getApp()
     */
    public function getApp()
    {
        if (! is_null($this->getAppAlias())) {
            return $this->getWorkbench()->getApp($this->getAppAlias());
        } else {
            throw new RuntimeException('This page is not part of any app!');
        }
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getAppAlias()
     */
    public function getAppAlias()
    {
        return $this->appAlias;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setAppAlias()
     */
    public function setAppAlias($appAlias)
    {
        $this->appAlias = $appAlias;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::isUpdateable()
     */
    public function isUpdateable()
    {
        return $this->updateable;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setUpdateable()
     */
    public function setUpdateable(bool $true_or_false)
    {
        $this->updateable = $true_or_false;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getMenuParentId()
     */
    public function getMenuParentId()
    {
        if (is_null($this->menuParentId) && ! is_null($this->getMenuParentPage())) {
            $this->menuParentId = $this->getMenuParentPage()->getMenuParentId();
        }
        return $this->menuParentId;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setMenuParentId()
     */
    public function setMenuParentId($menuParentId)
    {
        $this->menuParentId = $menuParentId;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getMenuParentIdCms()
     */
    public function getMenuParentIdCms()
    {
        if (is_null($this->menuParentIdCms) && ! is_null($this->getMenuParentPage())) {
            $this->menuParentIdCms = $this->getMenuParentPage()->getMenuParentIdCms();
        }
        return $this->menuParentIdCms;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setMenuParentIdCms()
     */
    public function setMenuParentIdCms($menuParentIdCms)
    {
        $this->menuParentIdCms = $menuParentIdCms;
        return $this;
    }

    /**
     *
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getMenuParentAlias()
     */
    public function getMenuParentAlias()
    {
        if (is_null($this->menuParentAlias) && ! is_null($this->getMenuParentPage())) {
            $this->menuParentAlias = $this->getMenuParentPage()->getAliasWithNamespace();
        }
        return $this->menuParentAlias;
    }

    /**
     *
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setMenuParentAlias()
     */
    public function setMenuParentAlias($alias_with_namespace)
    {
        $this->menuParentAlias = $alias_with_namespace;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getMenuParentPage()
     */
    public function getMenuParentPage()
    {
        if (is_null($this->menuParentPage)) {
            if ($this->menuParentId) {
                $this->menuParentPage = $this->getWorkbench()->getCMS()->loadPageById($this->menuParentId);
                $this->setMenuParentIdCms($this->menuParentPage->getIdCms());
                $this->setMenuParentAlias($this->menuParentPage->getAliasWithNamespace());
            } elseif ($this->menuParentIdCms) {
                $this->menuParentPage = $this->getWorkbench()->getCMS()->loadPageByIdCms($this->menuParentIdCms);
                $this->setMenuParentId($this->menuParentPage->getId());
                $this->setMenuParentAlias($this->menuParentPage->getAliasWithNamespace());
            } elseif ($this->menuParentAlias) {
                $this->menuParentPage = $this->getWorkbench()->getCMS()->loadPageByAlias($this->menuParentAlias);
                $this->setMenuParentId($this->menuParentPage->getId());
                $this->setMenuParentIdCms($this->menuParentPage->getIdCms());
            }
        }
        return $this->menuParentPage;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setMenuParentPage()
     */
    public function setMenuParentPage(UiPageInterface $page)
    {
        $this->menuParentPage = $page;
        $this->setMenuParentId($page->getId());
        $this->setMenuParentIdCms($page->getIdCms());
        $this->setMenuParentAlias($page->getAliasWithNamespace());
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getMenuIndex()
     */
    public function getMenuIndex()
    {
        return $this->menuIndex;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setMenuIndex()
     */
    public function setMenuIndex($number)
    {
        $this->menuIndex = $number;
        return $this;
    }

    /**
     *
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getId()
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setId()
     */
    public function setId($uid)
    {
        $this->id = $uid;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getIdCms()
     */
    public function getIdCms()
    {
        return $this->idCms;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setIdCms()
     */
    public function setIdCms($idCms)
    {
        $this->idCms = $idCms;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getName()
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setName()
     */
    public function setName($string)
    {
        $this->name = $string;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getShortDescription()
     */
    public function getShortDescription()
    {
        return $this->shortDescription;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setShortDescription()
     */
    public function setShortDescription($string)
    {
        $this->shortDescription = $string;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getReplacesPageAlias()
     */
    public function getReplacesPageAlias()
    {
        return $this->replacesPageAlias;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setReplacesPageAlias()
     */
    public function setReplacesPageAlias($alias_with_namespace)
    {
        $this->replacesPageAlias = $alias_with_namespace;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::getContents()
     */
    public function getContents()
    {
        return $this->contents;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setContents()
     */
    public function setContents($string)
    {
        $this->contents = $string;
        $this->removeAllWidgets();
        $string = trim($string);
        if (substr($string, 0, 1) == '{' && substr($string, -1) == '}') {
            WidgetFactory::createFromUxon($this, UxonObject::fromAnything($string));
        }
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\AliasInterface::getAlias()
     */
    public function getAlias()
    {
        if (is_null($this->alias) && ! is_null($this->getAliasWithNamespace())) {
            if (($sepPos = strrpos($this->getAliasWithNamespace(), NameResolver::NAMESPACE_SEPARATOR)) !== false) {
                $this->alias = substr($this->getAliasWithNamespace(), $sepPos + 1);
            } else {
                $this->alias = $this->getAliasWithNamespace();
            }
        }
        return $this->alias;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\AliasInterface::getAliasWithNamespace()
     */
    public function getAliasWithNamespace()
    {
        return $this->aliasWithNamespace;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\Model\UiPageInterface::setAliasWithNamespace()
     */
    public function setAliasWithNamespace($aliasWithNamespace)
    {
        $this->aliasWithNamespace = $aliasWithNamespace;
        return $this;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\AliasInterface::getNamespace()
     */
    public function getNamespace()
    {
        if (is_null($this->namespace) && ! is_null($this->getAliasWithNamespace())) {
            if (($sepPos = strrpos($this->getAliasWithNamespace(), NameResolver::NAMESPACE_SEPARATOR)) !== false) {
                $this->namespace = substr($this->getAliasWithNamespace(), 0, $sepPos);
            } else {
                $this->namespace = '';
            }
        }
        return $this->namespace;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\iCanBeConvertedToUxon::exportUxonObject()
     */
    public function exportUxonObject()
    {
        /** @var UxonObject $uxon */
        $uxon = $this->getWorkbench()->createUxonObject();
        $uxon->setProperty('id', $this->getId());
        $uxon->setProperty('alias', $this->getAliasWithNamespace());
        $uxon->setProperty('app_alias', $this->getAppAlias());
        $uxon->setProperty('updateable', $this->isUpdateable());
        $uxon->setProperty('menu_parent_id', $this->getMenuParentId());
        $uxon->setProperty('menu_parent_alias', $this->getMenuParentAlias());
        $uxon->setProperty('menu_index', $this->getMenuIndex());
        $uxon->setProperty('name', $this->getName());
        $uxon->setProperty('short_description', $this->getShortDescription());
        $uxon->setProperty('replaces_page_alias', $this->getReplacesPageAlias());
        $uxon->setProperty('contents', $this->getContents());
        
        return $uxon;
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Interfaces\iCanBeConvertedToUxon::importUxonObject()
     */
    public function importUxonObject(UxonObject $uxon)
    {
        $uxon->mapToClassSetters($this);
    }
}

?>
