<?php
namespace exface\Core\Widgets;
use exface\Core\Events\Workbench\OnCleanUpEvent;
use exface\Core\CommonLogic\Constants\Icons;
use exface\Core\CommonLogic\DataSheets\DataSheetMapper;
use exface\Core\CommonLogic\Model\UiPage;
use exface\Core\CommonLogic\UxonObject;
use exface\Core\DataTypes\ComparatorDataType;
use exface\Core\DataTypes\OfflineStrategyDataType;
use exface\Core\DataTypes\WidgetVisibilityDataType;
use exface\Core\Exceptions\Widgets\WidgetLogicError;
use exface\Core\Factories\DataSheetFactory;
use exface\Core\Factories\UiPageFactory;
use exface\Core\Factories\WidgetFactory;
use exface\Core\Interfaces\Model\UiPageInterface;
use exface\Core\Interfaces\Widgets\iHaveButtons;

/**
 * DataTable-configurators contain tabs for filters, sorters and column controls.
 *
 * In addition to the basic DataConfigurator which can be applied to any Data
 * widget, the DataTableConfigurator has a tab to control the order and visibility
 * of table columns.
 * 
 * TODO the aggregations control tab is not available yet
 *
 * @author Andrej Kabachnik, Georg Bieger
 *
 * @method \exface\Core\Widgets\DataTable getWidgetConfigured()
 *
 */
class DataTableConfigurator extends DataConfigurator
{
    private $tabColumns = null;
    private UxonObject|null $columnsUxon = null;
    private int $columnsDefaultVisibility = WidgetVisibilityDataType::OPTIONAL;

    private $aggregation_tab = null;

    private $tabSetups = null;
    private $setupsDisabled = false;
    private $setupsUxon = null;
    
    private ?Button $buttonSaveSetup = null;


    /**
     * Converts widget setups of dialogs from the old page-based format to the new slug-based one.
     * 
     * Setups created before slugs were introduced are identified by the alias of the page and the
     * full autogenerated widget id - including the prefix of the dialog the widget lives in. Since
     * the same dialog can be opened from different places, these setups must now be identified by
     * the alias of the action showing the dialog and the widget id within that dialog.
     * 
     * Setups of widgets sitting directly on a page are already in the correct format and are left
     * alone.
     * 
     * Regardless of the format, every setup is also checked for being orphaned via a cheap existence
     * check: if its slug no longer points to an existing screen (neither a page nor an object action
     * with that alias exists), the `ORPHANED_FLAG` is set - and cleared again once the screen exists.
     * Old-format setups whose page still exists but whose widget cannot be found are counted as "could
     * not be resolved" and flagged as orphaned too.
    * Older duplicates with the same creator, name, slug, widget id and object are also flagged as
    * orphaned; the newest setup remains active.
     * 
     * The behavior is controlled via the following config options of `exface.Core`:
     * 
     * - `WIDGETS.SETUPS.CLEANUP.ENABLED` - set to FALSE to skip this cleanup entirely.
     * - `WIDGETS.SETUPS.CLEANUP.DRY_RUN` - if TRUE (default), only reports what would be converted
     * without changing any data. Set to FALSE to actually persist the conversion.
     * - `WIDGETS.SETUPS.CLEANUP.MAX_SEARCH_DEPTH` - how deep to search for a widget by its id.
     * Finding widgets is expensive and can run into infinite loops, so the search is bounded.
     * 
     * @param OnCleanUpEvent $event
     * @return void
     */
    public static function onCleanUp(OnCleanUpEvent $event) : void
    {


        $workbench = $event->getWorkbench();
        $config = $workbench->getConfig();

        // Do not run unless all config options are present.
        if (! $config->hasOption('WIDGETS.SETUPS.CLEANUP.ENABLED')
            || ! $config->hasOption('WIDGETS.SETUPS.CLEANUP.DRY_RUN')
            || ! $config->hasOption('WIDGETS.SETUPS.CLEANUP.MAX_SEARCH_DEPTH')
        ) {
            return;
        }
        if ($config->getOption('WIDGETS.SETUPS.CLEANUP.ENABLED') !== true) {
            return;
        }
        $dryRun = $config->getOption('WIDGETS.SETUPS.CLEANUP.DRY_RUN') !== false;
        $maxDepth = (int) $config->getOption('WIDGETS.SETUPS.CLEANUP.MAX_SEARCH_DEPTH');

        $ds = DataSheetFactory::createFromObjectIdOrAlias($workbench, 'exface.Core.WIDGET_SETUP');
        $ds->getColumns()->addMultiple(['UID', 'NAME', 'SLUG', 'WIDGET_ID', 'OBJECT', 'ORPHANED_FLAG', 'CREATED_BY_USER', 'MODIFIED_ON']);
        $ds->dataRead();

        // Keep only the newest setup per creator/name/screen/widget/object combination.
        $duplicateUids = [];
        $newestRowsByDuplicateKey = [];
        foreach ($ds->getRows() as $row) {
            $duplicateKey = json_encode([
                $row['CREATED_BY_USER'] ?? null,
                $row['NAME'] ?? null,
                $row['SLUG'] ?? null,
                $row['WIDGET_ID'] ?? null,
                $row['OBJECT'] ?? null
            ]);
            $newestRow = $newestRowsByDuplicateKey[$duplicateKey] ?? null;
            if ($newestRow === null) {
                $newestRowsByDuplicateKey[$duplicateKey] = $row;
                continue;
            }

            $rowOrphaned = (int) ($row['ORPHANED_FLAG'] ?? 0);
            $newestOrphaned = (int) ($newestRow['ORPHANED_FLAG'] ?? 0);
            $rowModifiedOn = $row['MODIFIED_ON'] ?? '';
            $newestModifiedOn = $newestRow['MODIFIED_ON'] ?? '';
            $rowIsNewer = $rowOrphaned < $newestOrphaned
                || ($rowOrphaned === $newestOrphaned && (
                    $rowModifiedOn > $newestModifiedOn
                    || ($rowModifiedOn === $newestModifiedOn && ($row['UID'] ?? '') > ($newestRow['UID'] ?? ''))
                ));
            if ($rowIsNewer) {
                $duplicateUids[$newestRow['UID']] = true;
                $newestRowsByDuplicateKey[$duplicateKey] = $row;
            } else {
                $duplicateUids[$row['UID']] = true;
            }
        }

        // Existence-based orphan detection (independent of the old/new format): a setup is orphaned
        // if its slug no longer points to an existing screen - i.e. neither a page (page alias) nor
        // an object action (action alias) with that alias exists anymore. This does not resolve the
        // actual widget, so it is cheap.
        $slugs = array_values(array_unique(array_filter(array_column($ds->getRows(), 'SLUG'), function($s) {
            return $s !== null && $s !== '';
        })));
        $existingScreens = [];
        if (! empty($slugs)) {
            $pageSheet = DataSheetFactory::createFromObjectIdOrAlias($workbench, 'exface.Core.PAGE');
            $pageSheet->getColumns()->addFromExpression('ALIAS');
            $pageSheet->getFilters()->addConditionFromValueArray('ALIAS', $slugs);
            $pageSheet->dataRead();
            foreach ($pageSheet->getColumnValues('ALIAS') as $alias) {
                $existingScreens[$alias] = true;
            }

            $actionSheet = DataSheetFactory::createFromObjectIdOrAlias($workbench, 'exface.Core.OBJECT_ACTION');
            $actionSheet->getColumns()->addFromExpression('ALIAS_WITH_NS');
            $actionSheet->getFilters()->addConditionFromValueArray('ALIAS_WITH_NS', $slugs);
            $actionSheet->dataRead();
            foreach ($actionSheet->getColumnValues('ALIAS_WITH_NS') as $alias) {
                $existingScreens[$alias] = true;
            }
        }

        // Cache pages by slug to avoid instantiating the same widget tree more than once.
        $pages = [];
        $totalCnt = 0;
        $convertibleCnt = 0;
        $unresolvedCnt = 0;
        $screenGoneCnt = 0;
        $duplicateCnt = 0;
        $alreadyNewCnt = 0;
        $convertedUids = [];

        // Setups to update - only written to the data source when not a dry run.
        $updateSheet = DataSheetFactory::createFromObject($ds->getMetaObject());

        foreach ($ds->getRows() as $row) {
            $totalCnt++;
            $widgetId = $row['WIDGET_ID'] ?? '';
            $slug = $row['SLUG'] ?? '';
            $storedFlag = (int) ($row['ORPHANED_FLAG'] ?? 0);
            $updatedValues = [];

            $isDuplicate = isset($duplicateUids[$row['UID']]);
            $isOrphan = $isDuplicate || $slug === '' || ! isset($existingScreens[$slug]);
            if ($isDuplicate) {
                $duplicateCnt++;
            } elseif ($isOrphan) {
                $screenGoneCnt++;
            } elseif ($widgetId !== '' && stripos($widgetId, 'button') !== false) {
                // Old-format candidate: the slug was the alias of the page the widget lived on and the
                // widget id includes the prefix of the button that opened the dialog.
                if (! array_key_exists($slug, $pages)) {
                    try {
                        $pages[$slug] = UiPageFactory::createFromModel($workbench, $slug);
                    } catch (\Throwable $e) {
                        $pages[$slug] = null;
                    }
                }
                $page = $pages[$slug];
                if ($page === null) {
                    // Slug exists as an action, but not as a page - already converted.
                    $alreadyNewCnt++;
                } else {
                    // Finding a widget by its full autogenerated id can be very expensive and even run
                    // into infinite loops if the widget no longer exists. Bound the search depth.
                    try {
                        $widget = $page->getWidget($widgetId, null, $maxDepth);
                        $container = $widget->findUiContainer();
                        if ($container instanceof UiPageInterface) {
                            // Widget sits directly on the page - already in the correct format.
                            $alreadyNewCnt++;
                        } else {
                            if (! $dryRun) {
                                $updatedValues = [
                                    'SLUG' => $container->getSlug(),
                                    'WIDGET_ID' => $widget->getIdWithinUiContainer()
                                ];
                            }
                            $convertedUids[] = $row['UID'];
                            $convertibleCnt++;
                        }
                    } catch (\Throwable $e) {
                        // Page exists, but the widget could not be found - treat as orphaned.
                        $unresolvedCnt++;
                        $isOrphan = true;
                    }
                }
            } else {
                // Page setup or already converted new-format dialog setup.
                $alreadyNewCnt++;
            }

            // Reconcile the orphaned flag in both directions (set when orphaned, clear when found).
            $newFlag = $isOrphan ? 1 : 0;
            if ($newFlag !== $storedFlag && ! $dryRun) {
                $updatedValues['ORPHANED_FLAG'] = $newFlag;
            }
            if (! empty($updatedValues)) {
                $updateSheet->addRow(array_merge([
                    'UID' => $row['UID'],
                    'MODIFIED_ON' => $row['MODIFIED_ON']
                ], $updatedValues));
            }
        }

        // if its not a dry run, save the results
        if (! $dryRun && ! $updateSheet->isEmpty()) {
            $updateSheet->dataUpdate();
        }

        $event->addResultMessage('Widget setup cleanup (' . ($dryRun ? 'dry run' : 'applied') . '): read ' . $totalCnt . ' setup(s) - ' . $convertibleCnt . ($dryRun ? ' can be converted to the new format' : ' converted to the new format') . ', ' . ($unresolvedCnt + $screenGoneCnt + $duplicateCnt) . ' orphaned (' . $unresolvedCnt . ' could not be resolved, ' . $screenGoneCnt . ' screen removed, ' . $duplicateCnt . ' duplicate), ' . $alreadyNewCnt . ' already in the new format.' . (empty($convertedUids) ? '' : ' Converted UIDs: ' . implode(', ', $convertedUids) . '.'));
    }

    /**
     * {@inheritDoc}
     * @see DataConfigurator::initTabs()
     */
    protected function initTabs() : void
    {
        parent::initTabs();

        // Setups tab
        $tab = $this->createTab();
        $tab->setCaption($this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_CAPTION'));
        $tab->setIcon(Icons::STAR);
        $this->tabSetups = $tab;
        $this->addTab($tab, 0);

        // Columns tab
        $tab = $this->createTab();
        $tab->setCaption($this->translate('WIDGET.DATACONFIGURATOR.COLUMN_TAB_CAPTION'));
        $tab->setIcon(Icons::TABLE);
        $this->tabColumns = $tab;
        $this->addTab($tab);
    }

    public function getWidgets(callable $filter_callback = null): array
    {
        if (! $this->isDisabled()) {
            // Make sure to initialize setups and columns tabs if we might need them
            $this->getSetupsTab();
            $this->getOptionalColumnsTab();
        }
        return parent::getWidgets($filter_callback);
    }

    /**
     * @return Tab|null
     */
    public function getOptionalColumnsTab() : ?Tab
    {
        if ($this->isDisabled()) {
            $this->tabColumns->setHidden(true);
            return $this->tabColumns;
        }
        if ($this->tabColumns->isEmpty()){
            $this->initColumns($this->tabColumns);
        }
        return $this->tabColumns;
    }

    public function getOptionalColumns() : array
    {
        return $this->getOptionalColumnsTab()->getWidgets();
    }

    public function setOptionalColumns(UxonObject $arrayOfColumns) : DataTableConfigurator
    {
        $this->columnsUxon = $arrayOfColumns;
        return $this;
    }
    
    public function getOptionalColumnsUxon() : ?UxonObject
    {
        return $this->columnsUxon;
    }

    public function hasOptionalColumns() : bool
    {
        return $this->columnsUxon !== null && $this->columnsUxon->isEmpty() === false;
    }

    public function addOptionalColumn(DataColumn $column) : DataTableConfigurator
    {
        $alias = $column->getAttributeAlias();
        $columnExists = false;

        $tab = $this->tabColumns; // Do not use getOptionalColumnsTab() here to avoid infinite loop
        foreach ($tab->getWidgets() as $existingColumn) {
            if($alias === $existingColumn->getAttributeAlias()) {
                $columnExists = true;
                break;
            }
        }

        $configuredWidget = $this->getWidgetConfigured();
        foreach($configuredWidget->getColumns() as $existingColumn) {
            if($alias === $existingColumn->getAttributeAlias()) {
                $columnExists = true;
                break;
            }
        }
        
        if($columnExists) {
            return $this;
        }

        $tab->addWidget($column);
        $column->setParent($configuredWidget);
        return $this;
    }

    /**
     *
     * @return \exface\Core\Widgets\DataTableConfigurator
     */
    protected function initColumns(Tab $tab) : DataTableConfigurator
    {
        if (! $this->hasOptionalColumns()) {
            return $this;
        }
        $table = $this->getWidgetConfigured();
        // Do not create the columns for the table itself because that would reserve column
        // ids in the main column group, eventually resulting in shifting ids when optional
        // columns are added. Instead, create a detached column group and use that.
        // Using a column group makes it automatically possible to use attribute_group_alias
        // with the list of optional columns for the configurator!
        $colGrp = WidgetFactory::createFromUxonInParent(
            $table, 
            new UxonObject([
                'visibility' => WidgetVisibilityDataType::OPTIONAL
            ]), 
            'DataColumnGroup'
        );

        foreach($arr = $this->columnsUxon->toArray() as $key => $value) {
            if($value['visibility'] === null) {
                $arr[$key]['visibility'] = $this->columnsDefaultVisibility;
            }
        }

        $colGrp->importUxonObject(new UxonObject(['columns' => $arr]));
        foreach ($colGrp->getColumns() as $column) {
            $this->addOptionalColumn($column);
        }

        return $this;
    }

    /**
     *
     * @return Tab
     */
    public function getAggregationTab()
    {
        if (is_null($this->aggregation_tab)){
            $this->aggregation_tab = $this->createAggregationTab();
            $this->addTab($this->aggregation_tab, 4);
        }
        return $this->tabColumns;
    }

    /**
     *
     * @return Tab
     */
    protected function createAggregationTab()
    {
        $tab = $this->createTab();
        $tab->setCaption($this->translate('WIDGET.DATACONFIGURATOR.AGGREGATION_TAB_CAPTION'));
        $tab->setIcon(Icons::OBJECT_GROUP);
        // TODO re-enable the tab once it has content
        $tab->setDisabled(true);
        return $tab;
    }

    /**
     * @return Tab|null
     */
    public function getSetupsTab() : ?Tab
    {
        if (! $this->hasSetups()) {
            $this->tabSetups->setHidden(true);
            return $this->tabSetups;
        }
        if ($this->tabSetups->isEmpty()) {
            try {
                $this->initSetupsTable($this->tabSetups);
            } catch (\Throwable $e) {
                $this->getWorkbench()->getLogger()->logException(new WidgetLogicError($this->getDataWidget(), 'Error instantiating setups table. ' . $e->getMessage(), null, $e));
            }
        }
        return $this->tabSetups;
    }

    /**
     *
     * @return Tab
     */
    protected function initSetupsTable(Tab $tab) : Tab
    {
        $dataWidget = $this->getDataWidget();

        $screenSlug = $dataWidget->findUiContainer()->getSlug();
        $widgetId = $dataWidget->getIdWithinUiContainer();
        $objectId = $dataWidget->getMetaObject()->getId();
        
        /* @var $table \exface\Core\Widgets\DataTableResponsive */
        $table = WidgetFactory::createFromUxonInParent($tab, new UxonObject([
            'widget_type' => 'DataTableResponsive',
            'object_alias' => 'exface.Core.WIDGET_SETUP',
            'paginate' => false,
            'configurator_setups_enabled' => false,
            'hide_caption' => true,
            'lazy_loading_action' => [
                'alias' => 'exface.Core.ReadData',
                'offline_strategy' => OfflineStrategyDataType::IGNORE
            ],
            'filters' => [
                [
                    'attribute_alias' => 'SLUG',
                    'comparator' => ComparatorDataType::EQUALS,
                    'value' => $screenSlug,
                    'hidden' => true
                ],
                [
                    'attribute_alias' => 'ORPHANED_FLAG',
                    'comparator' => ComparatorDataType::EQUALS_NOT,
                    'value' => true,
                    'hidden' => true
                ], 
                [
                    'attribute_alias' => 'WIDGET_ID',
                    'comparator' => ComparatorDataType::EQUALS,
                    'value' => $widgetId,
                    'hidden' => true
                ], 
                [
                    'attribute_alias' => 'OBJECT',
                    'comparator' => ComparatorDataType::EQUALS,
                    'value' => $objectId,
                    'hidden' => true
                ], [
                    'hidden' => true,
                    'condition_group' => [
                        'operator' => EXF_LOGICAL_OR,
                        'conditions' => [
                            [
                                'expression' => 'PRIVATE_FOR_USER',
                                'comparator' => ComparatorDataType::EQUALS,
                                'value' => $this->getWorkbench()->getSecurity()->getAuthenticatedUser()->getUid()
                            ], 
                            [
                                'expression' => 'PRIVATE_FOR_USER',
                                'comparator' => ComparatorDataType::EQUALS,
                                'value' => EXF_LOGICAL_NULL
                            ], 
                            [
                                'expression' => 'WIDGET_SETUP_USER__USER__UID',
                                'comparator' => ComparatorDataType::EQUALS,
                                'value' => $this->getWorkbench()->getSecurity()->getAuthenticatedUser()->getUid(),
                                'apply_to_aggregates' => true
                            ]
                        ]
                    ]
                ]
            ],
            'columns' => [
                [
                    'data_column_name' => 'SETUP_APPLIED',
                    'caption' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_ACTIVE'),
                    'value' => '',
                    'align' => 'Center',
                    'readonly' => true,
                    "cell_widget" => [
                      "widget_type" => "Icon"
                    ]
                ], [
                    'attribute_alias' => 'NAME',
                ], [
                    'attribute_alias' => 'WIDGET_SETUP_USER__FAVORITE_FLAG',
                    'readonly' => true
                ], [
                    'attribute_alias' => 'VISIBILITY',
                    'caption' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_VISIBILITY'),
                ], [
                    'attribute_alias' => 'DESCRIPTION',
                    'caption' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_SETUP_DESC_PLACEHOLDER'),
                    'nowrap' => false
                ],
                [
                    'attribute_alias' => 'MODIFIED_ON',
                    'caption' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_MODIFIED_ON'),
                    'readonly' => true
                ], [
                    'attribute_alias' => 'SLUG',
                    'hidden' => true
                ], [
                    'attribute_alias' => 'WIDGET_ID',
                    'hidden' => true
                ], [
                    'attribute_alias' => 'OBJECT',
                    'hidden' => true
                ], [
                    'attribute_alias' => 'SETUP_UXON',
                    'hidden' => true
                ], [
                    'attribute_alias' => 'UID',
                    'hidden' => true
                ],[
                    'attribute_alias' => 'WIDGET_SETUP_USER__UID',
                    'readonly' => true,
                    'hidden' => true
                ], [
                    'attribute_alias' => 'CREATED_BY_USER',
                    'readonly' => true,
                    'hidden' => true
                ],[
                    'attribute_alias' => 'WIDGET_SETUP_USER__MODIFIED_ON',
                    'readonly' => true,
                    'hidden' => true
                ]
            ]
        ]));
        $table->setHideHelpButton(true);
        $this->buttonSaveSetup = $this->createButtonToSaveSetup($table);
        $mainToolbar = $table->getToolbarMain();
        $mainToolbar
            ->setIncludeNoExtraActions(true)
            ->addButton($this->createButtonToApplySetup($table))
            ->addButton($this->buttonSaveSetup)
            ->addButton($this->createButtonToUpdateSetup($table))
            ->addButton($this->createButtonToFavoriteSetup($table))
            ->addButton($this->createButtonToShareSetup($table))
            ->addButton($this->createButtonToPublishSetup($table))
            ->addButton($this->createButtonToEditSetup($table))
            ->addButton($this->createButtonToDeleteSetup($table));
        $tab->addWidget($table);
        return $tab;
    }
    
    protected function createButtonToApplySetup(iHaveButtons $table) : Button
    {
        return $table->createButton(new UxonObject([
            'caption' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_APPLY'),
            'hint' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_APPLY_HINT'),
            'icon' => 'check-circle-o',
            'visibility' => WidgetVisibilityDataType::PROMOTED,
            'bind_to_double_click' => true,
            'action' => $this->buildUxonForActionApplySetup()
        ]));
    }
    
    protected function createButtonToSaveSetup(iHaveButtons $table) : Button
    {
        return $table->createButton(new UxonObject([
            'caption' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_SAVE'),
            'hint' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_SAVE_HINT'),
            'icon' => 'bookmark-o',
            'action' => $this->buildUxonForActionSaveSetup()
        ]));
    }
    
    protected function createButtonToUpdateSetup(iHaveButtons $table) : Button
    {
        return $table->createButton(new UxonObject([
            'caption' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_UPDATE'),
            'hint' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_UPDATE_HINT'),
            'icon' => 'refresh',
            'action' => $this->buildUxonForActionUpdateSetup(),
            "disabled_if" => [
                "operator" => EXF_LOGICAL_OR,
                "conditions" => [
                    [
                        "value_left" => "=~input!CREATED_BY_USER",
                        "comparator" => "!==",
                        "value_right" => $this->getWorkbench()->getSecurity()->getAuthenticatedUser()->getUid()
                    ],
                    [
                        "value_left" => "=~input!UID",
                        "comparator" => "==",
                        "value_right" => ""
                    ]
                ]
            ]
        ]));
    }
    
    /**
     * Button to update a widget_setup_user entry to mark/unmark the current setup as favorite for the current user.
     * @param iHaveButtons $table
     * @return Button
     */
    public function createButtonToFavoriteSetup(iHaveButtons $table) : Button
    {
        return $table->createButton(new UxonObject([
            'caption' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_FAVORITE'),
            'hint' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_FAVORITE_HINT'),
            'icon' => 'star',
            'hide_caption' => true,
            'action' => $this->buildUxonForActionFavoriteSetup()
        ]));
    }

    public function createButtonToShareSetup(iHaveButtons $table) : Button
    {
        return $table->createButton(new UxonObject([
            'hide_caption' => true,
            'icon' => 'share',
            'action' => $this->buildUxonForActionShareSetup()
        ]));
    }

    public function createButtonToPublishSetup(iHaveButtons $table) : Button
    {
        return $table->createButton(new UxonObject([
            'hide_caption' => true,
            'icon' => 'globe',
            'action' => $this->buildUxonForActionPublishSetup(),
            'hint' => $this->translate('WIDGET.DATACONFIGURATOR.SETUPS_TAB_PUBLISH_HINT')
        ]));
    }

    public function createButtonToEditSetup(iHaveButtons $table) : Button
    {
        return $table->createButton(new UxonObject([
            'hide_caption' => true,
            'action' => $this->buildUxonForActionEditSetup()
        ]));
    }

    public function createButtonToDeleteSetup(iHaveButtons $table) : Button
    {
        return $table->createButton(new UxonObject([
            'hide_caption' => true,
            'caption' => $this->translate('ACTION.DELETEOBJECT.NAME'),
            'icon' => 'trash-o',
            'disabled_if' => [
                'operator' => 'AND',
                'conditions' => [
                    [
                        "value_left" => "=~input!CREATED_BY_USER",
                        "comparator" => "!==",
                        "value_right" => $this->getWorkbench()->getSecurity()->getAuthenticatedUser()->getUid()
                    ]
                ]
            ],
            'action' => $this->buildUxonForActionDeleteSetup()
        ]));
    }

    public function setSetups(UxonObject $arrayOfSetups) : DataTableConfigurator
    {
        $this->setupsUxon = $arrayOfSetups;
        return $this;
    }

    /**
     * Set to FALSE to disable saving/loading widget setups entirely
     *
     * @uxon-property setups_enabled
     * @uxon-type boolean
     * @uxon-default true
     *
     * @param bool $trueOrFalse
     * @return $this
     */
    public function setSetupsEnabled(bool $trueOrFalse) : DataTableConfigurator
    {
        $this->setupsDisabled = ! $trueOrFalse;
        return $this;
    }

    public function hasSetups() : bool
    {
        return $this->setupsDisabled === false && ! $this->isDisabled() && $this->getDataWidget()->getConfiguratorSetupsEnabled() === true;
    }

    /**
     * Returns the ID of the setups table, or null if setups are disabled
     *
     * @return string|null
     */
    public function getSetupsTableId() : ?string
    {
        if (!$this->hasSetups()){
            return null;
        }
        else{
            return $this->getSetupsTab()->getWidgetFirst()->getId();
        }
    }
    
    protected function buildUxonForActionSaveSetup() : array
    {
        return [
            'alias' => "exface.core.ShowObjectCreateDialog",
            'offline_strategy' => OfflineStrategyDataType::IGNORE,
            "input_rows_min" => 0,
            "input_rows_max" => 1,
            "input_object_alias" => "exface.Core.WIDGET_SETUP",
            "dialog" => [
                "width" => 1,
                "height" => "auto",
                "columns_in_grid" => 1,
                "widgets" => [
                    [
                        "attribute_alias" => "NAME"
                    ],
                    [
                        "attribute_alias" => "DESCRIPTION",
                        "caption" => $this->translate("WIDGET.DATACONFIGURATOR.SETUPS_TAB_SETUP_DESC_PLACEHOLDER")
                    ]
                ],
                "buttons" => [
                    [
                        "caption" => $this->translate("WIDGET.DATACONFIGURATOR.SETUPS_TAB_SETUP_NAME_PROMPT_TITLE"),
                        "visibility" => "promoted",
                        "align" => "opposite",
                        'icon' => 'bookmark-o',
                        "action" => [
                            "alias" => "exface.Core.ActionChain",
                            "offline_strategy" => OfflineStrategyDataType::IGNORE,
                            'use_result_of_action' => 1,
                            "actions" => [
                                [
                                    "alias" => "exface.Core.CallWidgetFunction",
                                    "widget_id" => $this->getDataWidget()->getIdAutogenerated(),
                                    "widget_id_space" => UiPage::WIDGET_ID_SEPARATOR, // Root id space because we are using the autogenerated id!
                                    "function" => DataTable::FUNCTION_DUMP_SETUP . "(SETUP_UXON, SLUG, WIDGET_ID, PROTOTYPE_FILE, OBJECT, PRIVATE_FOR_USER)"
                                ],
                                [
                                    "alias" => "exface.Core.ActionChain",
                                    'use_result_of_action' => 0,
                                    "actions" => [
                                        [
                                            "alias" => "exface.Core.CreateData"
                                        ],
                                        [
                                            "alias" => "exface.Core.CreateData",
                                            "object_alias" => "exface.Core.WIDGET_SETUP_USER",
                                            "input_mapper" => [
                                                "column_to_column_mappings" => [
                                                    [
                                                        "from" => "UID",
                                                        "to" => "WIDGET_SETUP"
                                                    ],
                                                    [
                                                        "from" => "CREATED_BY_USER",
                                                        "to" => "USER"
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ],
                                [
                                    'alias' => "exface.Core.CallWidgetFunction",
                                    'widget_id' => $this->getDataWidget()->getIdAutogenerated(),
                                    "widget_id_space" => UiPage::WIDGET_ID_SEPARATOR,
                                    'function' => "apply_setup([#SETUP_UXON#])"
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ];
    }
    
    protected function buildUxonForActionUpdateSetup() : array
    {
        return [
            'offline_strategy' => OfflineStrategyDataType::IGNORE,
            "input_rows_min" => 1,
            "input_rows_max" => 1,
            "input_object_alias" => "exface.Core.WIDGET_SETUP",
            "alias" => "exface.Core.ActionChain",
            "actions" => [
                [
                    "alias" => "exface.Core.CallWidgetFunction",
                    "widget_id" => $this->getDataWidget()->getIdAutogenerated(),
                    "function" => "dump_setup(SETUP_UXON, SLUG, WIDGET_ID, PROTOTYPE_FILE, OBJECT, PRIVATE_FOR_USER, true)"
                ],
                [
                    "alias" => "exface.Core.UpdateData",
                    "object_alias" => "exface.Core.WIDGET_SETUP"
                ]
            ]
        ];
    }

    protected function buildUxonForActionDeleteSetup() : array
    {
        return [
            'offline_strategy' => OfflineStrategyDataType::IGNORE,
            "input_rows_min" => 1,
            "input_rows_max" => 1,
            "input_object_alias" => "exface.Core.WIDGET_SETUP",
            "alias" => "exface.Core.ActionChain",
            "confirmation_for_action" => [
                "caption" => $this->translate('ACTION.DELETEOBJECT.CONFIRMATION_TITLE'),
                "widget_type" => "ConfirmationMessage",
                "text" => $this->translate('ACTION.DELETEOBJECT.CONFIRMATION_TEXT'),
                "button_continue" => [
                    "caption" => "Ok"
                ]
            ],
            "actions" => [
                [
                    "alias" => "exface.Core.CallWidgetFunction",
                    "widget_id" => $this->getDataWidget()->getIdAutogenerated(),
                    "function" => "clear_applied_setup()"
                ],
                [
                    "alias" => "exface.Core.DeleteObject",
                    "object_alias" => "exface.Core.WIDGET_SETUP"
                ]
            ]
        ];
    }
    
    protected function buildUxonForActionApplySetup() : array
    {
        return [
            'alias' => "exface.Core.CallWidgetFunction",
            "input_rows_min" => 1,
            "input_rows_max" => 1,
            'offline_strategy' => OfflineStrategyDataType::IGNORE,
            'widget_id' => $this->getDataWidget()->getIdAutogenerated(),
            'function' => "apply_setup([#SETUP_UXON#])"
        ];
    }
    
    protected function buildUxonForActionShareSetup() : array
    {
        return [
            'alias' => "exface.Core.WidgetSetupShareForUsers"
        ];
    }

    protected function buildUxonForActionPublishSetup() : array
    {
        return [
            'alias' => "exface.Core.WidgetSetupPublishDialogForUsers"
        ];
    }

    protected function buildUxonForActionEditSetup() : array
    {
        return [
            'alias' => 'exface.Core.WidgetSetupEditForUsers',
            // Make sure to use system columns for prefill only. DO NOT use WIDGET_SETUP_USER__FAVORITE_FLAG
            // and similar because they will produce errors when trying to read missing data. These columns
            // only work here because of the user filter!
            'input_mapper' => [
                'inherit_columns' => DataSheetMapper::INHERIT_COLUMNS_OWN_SYSTEM_ATTRIBUTES
            ]
        ];
    }
    
    protected function buildUxonForActionFavoriteSetup() : array
    {
        return [
            "alias" => "exface.Core.SaveData",
            'offline_strategy' => OfflineStrategyDataType::IGNORE,
            "object_alias" => "exface.Core.WIDGET_SETUP_USER",
            "input_rows_min" => 1,
            "input_rows_max" => 1,
            "input_mapper" => [
                "from_object_alias" => "exface.Core.WIDGET_SETUP",
                "to_object_alias" => "exface.Core.WIDGET_SETUP_USER",
                "column_to_column_mappings" => [
                    [
                        "from" => "USER_ENTRY_FOR_CURRENT_USER__UID",
                        "to" => "UID"
                    ],
                    [
                        "from" => "USER_ENTRY_FOR_CURRENT_USER__MODIFIED_ON",
                        "to" => "MODIFIED_ON"
                    ],
                    [
                        "from" => "=Not(IfNull(USER_ENTRY_FOR_CURRENT_USER__FAVORITE_FLAG, 0))",
                        "to" => "FAVORITE_FLAG"
                    ],
                    [
                        "from" => "'" . $this->getWorkbench()->getSecurity()->getAuthenticatedUser()->getUid() . "'",
                        "to" => "USER"
                    ],
                    [
                        "from" => "UID",
                        "to" => "WIDGET_SETUP"
                    ],
                ]
            ]
        ];
    }

    /**
     * @return Button|null
     */
    public function getButtonToSaveSetup() : ?Button
    {
        if (! $this->hasSetups()) {
            return null;
        }
        if ($this->buttonSaveSetup === null) {
            $this->initSetupsTable($this->tabSetups);
        }
        return $this->buttonSaveSetup;
    }
}