<?php
namespace exface\Core\Actions;

use exface\Core\Widgets\Dialog;
use exface\Core\CommonLogic\UxonObject;
use exface\Core\DataTypes\WidgetVisibilityDataType;
use exface\Core\CommonLogic\Constants\Icons;

/**
 * Shows an advanced search dialog allowing the user to search and select data entries.
 * 
 * The seleted UIDs will be sent to the `target_widget_id` overriding it's current value. 
 * Any widget can be used as target. The `multi_select` property of the action controls
 * if the user will be able to select multiple items. By default, this setting will be
 * inherited from the target widget (if it supports multi-select).
 * 
 * If no `widget` is specified by the user, the action will produce an autogenerated
 * `DataLookupDialog` - a search dialog based on default-display settings in the metamodel 
 * of the object being searched. This basically means, that the lookup-dialog will show the 
 * same table as the `InputComboTable` and provide filter over every visible column.
 * 
 * You can customize the lookup dialog by specifying a custom `widget` for the action:
 * 
 * ```
 *  {
 *      "alias": "exface.Core.ShowLookupDialog",
 *      "widget": {
 *          "object_alias": "...",
 *          "widget_type": "DataTable",
 *          "filters": [
 *              {
 *                "attribute_alias": "..."
 *              }
 *          ],
 *          "columns": [
 *              {
 *                "attribute_alias": "..."
 *              }
 *          ]
 *      }
 *  }
 * 
 * ```
 *
 * @author Andrej Kabachnik
 * @author Stefan Leupold
 * @author Thomas Michael
 *        
 */
class ShowLookupDialog extends ShowDialog
{
    private $target_widget_id = null;
    
    private $multi_select = null;

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Actions\ShowWidget::init()
     */
    protected function init()
    {
        parent::init();
        $this->setPrefillWithInputData(false);
        $this->setIcon(Icons::SEARCH);
        
        if ($this->isDefinedInWidget() === true && $this->getWidgetDefinedIn()->is('DialogButton')) {
            $this->getWidgetDefinedIn()->setCloseDialogAfterActionSucceeds(false);
        }
    }
    
    /**
     *
     * {@inheritDoc}
     * @see \exface\Core\Actions\ShowDialog::getDefaultWidgetType()
     */
    public function getDefaultWidgetType() : ?string
    {
        return 'DataLookupDialog';
    }

    /**
     * 
     * {@inheritDoc}
     * @see \exface\Core\Actions\ShowDialog::enhanceDialogWidget()
     */
    protected function enhanceDialogWidget(Dialog $dialog)
    {
        $dialog = parent::enhanceDialogWidget($dialog);
        
        if ($this->getMultiSelect() !== null) {
            $dialog->setMultiSelect($this->getMultiSelect());
        }
        
        /* @var $data_table \exface\Core\Widgets\DataTable */
        $data_table = $dialog->getDataWidget();
        
        $btnUxon = new UxonObject([
            'caption' => $this->getWorkbench()->getCoreApp()->getTranslator()->translate("ACTION.SHOWLOOKUPDIALOG.SAVE_BUTTON"),
            'visibility' => WidgetVisibilityDataType::PROMOTED,
            'icon' => Icons::CHECK,
            'action' => [
                'alias' => 'exface.Core.SendToWidget',
                'target_widget_id' => $this->getTargetWidgetId()
            ]
        ]);
        $dialog->addButton($dialog->createButton($btnUxon)->setInputWidget($data_table));
        
        /* TODO how to bind closing the dialog to a single click on a row for single-select lookups?
         * A table button will not close the dialog and a dialog-button cannot be bound to clicks on
         * a table...
        if ($data_table->getMultiSelect() === false) {
            $singleClickBtnUxon = $btnUxon->copy();
            $singleClickBtnUxon
                ->setProperty('visibility', WidgetVisibilityDataType::HIDDEN)
                ->setProperty('bind_to_left_click', true);
            $data_table->addButton($data_table->createButton($singleClickBtnUxon));
        }*/
        
        return $dialog;
    }

    /**
     *
     * @return boolean
     */
    public function getTargetWidgetId()
    {
        return $this->target_widget_id;
    }

    /**
     * The id of the widget to receive the selected values.
     *
     * @uxon-property target_widget_id
     * @uxon-type uxon:$..id
     *
     * @param boolean $value            
     * @return \exface\Core\Actions\ShowLookupDialog
     */
    public function setTargetWidgetId($value)
    {
        $this->target_widget_id = $value;
        return $this;
    }
    
    /**
     * Set to TRUE to allow selection of multiple entries in the lookup dialog.
     * 
     * If the lookup dialog is called from an input widget (e.g. `InputComboTable`) this setting
     * is inherited from that input. Otherwise it is `false` by default.
     * 
     * @uxon-property multi_select
     * @uxon-type boolean
     * @uxon-default false
     * 
     * @param bool $trueOrFalse
     * @return ShowLookupDialog
     */
    public function setMultiSelect(bool $trueOrFalse) : ShowLookupDialog
    {
        $this->multi_select = $trueOrFalse;
        return $this;
    }
    
    /**
     * 
     * @return bool|NULL
     */
    protected function getMultiSelect() : ?bool
    {
        return $this->multi_select;
    }
}